const fs = require('fs/promises');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const WWW_DIR = path.join(ROOT, 'www');

const STATIC_FILES = ['index.html', 'manifest.json', 'sw.js'];
const STATIC_DIRS = ['scripts', 'styles', 'icons'];
const STATIC_ASSET_IMAGE_ALLOWLIST = new Set([
  path.normalize('assets/icon-shop.jpg'),
  path.normalize('assets/icon-family.jpg')
]);
const REMOTE_VENUE_IMAGE_EXTENSIONS = new Set(['.jpg', '.jpeg', '.webp']);

async function removeDir(targetPath) {
  await fs.rm(targetPath, { recursive: true, force: true });
}

async function ensureDir(targetPath) {
  await fs.mkdir(targetPath, { recursive: true });
}

async function copyFileRelative(relativePath) {
  const sourcePath = path.join(ROOT, relativePath);
  const targetPath = path.join(WWW_DIR, relativePath);
  await ensureDir(path.dirname(targetPath));
  await fs.copyFile(sourcePath, targetPath);
}

async function copyDirRelative(relativePath) {
  const sourcePath = path.join(ROOT, relativePath);
  const targetPath = path.join(WWW_DIR, relativePath);
  await fs.cp(sourcePath, targetPath, { recursive: true });
}

async function copyAssetsRelative(relativePath = 'assets') {
  const sourcePath = path.join(ROOT, relativePath);
  const targetPath = path.join(WWW_DIR, relativePath);
  await ensureDir(targetPath);

  const entries = await fs.readdir(sourcePath, { withFileTypes: true });
  for (const entry of entries) {
    const childRelativePath = path.join(relativePath, entry.name);
    const normalizedRelativePath = path.normalize(childRelativePath);

    if (entry.isDirectory()) {
      await copyAssetsRelative(childRelativePath);
      continue;
    }

    const extension = path.extname(entry.name).toLowerCase();
    const isRemoteVenueImage = REMOTE_VENUE_IMAGE_EXTENSIONS.has(extension)
      && !STATIC_ASSET_IMAGE_ALLOWLIST.has(normalizedRelativePath);

    if (isRemoteVenueImage) {
      continue;
    }

    await copyFileRelative(childRelativePath);
  }
}

async function build() {
  let cartoApiKey = process.env.CARTO_BASEMAP_API_KEY?.trim();
  if (!cartoApiKey) {
    try {
      const config = JSON.parse(await fs.readFile(path.join(ROOT, 'map-config.local.json'), 'utf8'));
      cartoApiKey = typeof config.cartoApiKey === 'string' ? config.cartoApiKey.trim() : '';
    } catch (error) {
      if (error.code !== 'ENOENT') throw error;
    }
  }
  if (!cartoApiKey || cartoApiKey === 'YOUR_CARTO_KEY') {
    throw new Error('Set CARTO_BASEMAP_API_KEY or cartoApiKey in map-config.local.json before building.');
  }

  // The key is necessarily visible in client requests, but kept out of Git and logs.
  // Write it before copying scripts so root previews and both native builds agree.
  await fs.writeFile(
    path.join(ROOT, 'scripts', 'map-config.js'),
    `// Generated by build:web. Do not commit.\nwindow.FriendlySpacesMap = Object.freeze(${JSON.stringify({ cartoApiKey })});\n`
  );
  await removeDir(WWW_DIR);
  await ensureDir(WWW_DIR);

  for (const relativePath of STATIC_FILES) {
    await copyFileRelative(relativePath);
  }

  for (const relativePath of STATIC_DIRS) {
    await copyDirRelative(relativePath);
  }

  await copyFileRelative(path.join('data', 'venues.json'));
  await copyFileRelative(path.join('data', 'filters.json'));
  await copyFileRelative(path.join('data', 'content.json'));
  await copyAssetsRelative();
}

build().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
